openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: 'AWS Directory Service #X Amz Target=DirectoryService 20150416.AcceptSharedDirectory #X Amz Target=DirectoryService 20150416.AcceptSharedDirectory #X Amz Target=DirectoryService 20150416.ListIpRoutes API'
  description: <fullname>Directory Service</fullname> <p>Directory Service is a web service that makes it easy for you to setup and run directories in the Amazon Web Services cloud, or connect your Amazon Web Services resources with an existing self-managed Microsoft Active Directory. This guide provides detailed information about Directory Service operations, data types, parameters, and errors. For information about Directory Services features, see <a href="https://aws.amazon.com/directoryservice/">Directory Service</a> and the <a href="http://docs.aws.amazon.com/directoryservice/latest/admin-guide/what_is.html">Directory Service Administration Guide</a>.</p> <note> <p>Amazon Web Services provides SDKs that consist of libraries and sample code for various programming languages and platforms (Java, Ruby, .Net, iOS, Android, etc.). The SDKs provide a convenient way to create programmatic access to Directory Service and other Amazon Web Services services. For more information about the Amazon Web Services SDKs, including how to download and install them, see <a href="http://aws.amazon.com/tools/">Tools for Amazon Web Services</a>.</p> </note>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: ds
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/ds-2015-04-16.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://ds.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Directory Service multi-region endpoint
- url: https://ds.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Directory Service multi-region endpoint
- url: http://ds.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Directory Service endpoint for China (Beijing) and China (Ningxia)
- url: https://ds.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Directory Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=DirectoryService 20150416.ListIpRoutes'
paths:
  /#X-Amz-Target=DirectoryService_20150416.ListIpRoutes:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListIpRoutes
      description: Lists the address blocks that you have added to a directory.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListIpRoutesResult'
        '480':
          description: EntityDoesNotExistException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityDoesNotExistException'
        '481':
          description: InvalidNextTokenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidNextTokenException'
        '482':
          description: InvalidParameterException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterException'
        '483':
          description: ClientException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientException'
        '484':
          description: ServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListIpRoutesRequest'
      parameters:
      - name: Limit
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - DirectoryService_20150416.ListIpRoutes
      tags:
      - '#X Amz Target=DirectoryService 20150416.ListIpRoutes'
components:
  schemas:
    IpRouteStatusReason:
      type: string
    IpRouteInfo:
      type: object
      properties:
        DirectoryId:
          allOf:
          - $ref: '#/components/schemas/DirectoryId'
          - description: Identifier (ID) of the directory associated with the IP addresses.
        CidrIp:
          allOf:
          - $ref: '#/components/schemas/CidrIp'
          - description: IP address block in the <a>IpRoute</a>.
        IpRouteStatusMsg:
          allOf:
          - $ref: '#/components/schemas/IpRouteStatusMsg'
          - description: The status of the IP address block.
        AddedDateTime:
          allOf:
          - $ref: '#/components/schemas/AddedDateTime'
          - description: The date and time the address block was added to the directory.
        IpRouteStatusReason:
          allOf:
          - $ref: '#/components/schemas/IpRouteStatusReason'
          - description: The reason for the IpRouteStatusMsg.
        Description:
          allOf:
          - $ref: '#/components/schemas/Description'
          - description: Description of the <a>IpRouteInfo</a>.
      description: Information about one or more IP address blocks.
    ClientException: {}
    DirectoryId:
      type: string
      pattern: ^d-[0-9a-f]{10}$
    IpRouteStatusMsg:
      type: string
      enum:
      - Adding
      - Added
      - Removing
      - Removed
      - AddFailed
      - RemoveFailed
    ListIpRoutesRequest:
      type: object
      required:
      - DirectoryId
      title: ListIpRoutesRequest
      properties:
        DirectoryId:
          allOf:
          - $ref: '#/components/schemas/DirectoryId'
          - description: Identifier (ID) of the directory for which you want to retrieve the IP addresses.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: The <i>ListIpRoutes.NextToken</i> value from a previous call to <a>ListIpRoutes</a>. Pass null if this is the first call.
        Limit:
          allOf:
          - $ref: '#/components/schemas/Limit'
          - description: Maximum number of items to return. If this value is zero, the maximum number of items is specified by the limitations of the operation.
    AddedDateTime:
      type: string
      format: date-time
    Description:
      type: string
      pattern: ^([a-zA-Z0-9_])[\\a-zA-Z0-9_@#%*+=:?./!\s-]*$
      minLength: 0
      maxLength: 128
    IpRoutesInfo:
      type: array
      items:
        $ref: '#/components/schemas/IpRouteInfo'
    NextToken:
      type: string
    Limit:
      type: integer
      minimum: 0
    ServiceException: {}
    EntityDoesNotExistException: {}
    InvalidParameterException: {}
    InvalidNextTokenException: {}
    CidrIp:
      type: string
      pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([1-9]|[1-2][0-9]|3[0-2]))$
    ListIpRoutesResult:
      type: object
      properties:
        IpRoutesInfo:
          allOf:
          - $ref: '#/components/schemas/IpRoutesInfo'
          - description: A list of <a>IpRoute</a>s.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: If not null, more results are available. Pass this value for the <i>NextToken</i> parameter in a subsequent call to <a>ListIpRoutes</a> to retrieve the next set of items.
  parameters:
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/ds/
x-hasEquivalentPaths: true
