openapi: 3.2.0
info:
  version: 1.0.0
  x-release: v4
  title: 'AWS Directory Service #X Amz Target=DirectoryService 20150416.AcceptSharedDirectory #X Amz Target=DirectoryService 20150416.AcceptSharedDirectory #X Amz Target=DirectoryService 20150416.CreateTrust #X Amz Target=DirectoryService 20150416.CreateTrust #X Amz Target=DirectoryService 20150416.CreateTrust API'
  description: <fullname>Directory Service</fullname> <p>Directory Service is a web service that makes it easy for you to setup and run directories in the Amazon Web Services cloud, or connect your Amazon Web Services resources with an existing self-managed Microsoft Active Directory. This guide provides detailed information about Directory Service operations, data types, parameters, and errors. For information about Directory Services features, see <a href="https://aws.amazon.com/directoryservice/">Directory Service</a> and the <a href="http://docs.aws.amazon.com/directoryservice/latest/admin-guide/what_is.html">Directory Service Administration Guide</a>.</p> <note> <p>Amazon Web Services provides SDKs that consist of libraries and sample code for various programming languages and platforms (Java, Ruby, .Net, iOS, Android, etc.). The SDKs provide a convenient way to create programmatic access to Directory Service and other Amazon Web Services services. For more information about the Amazon Web Services SDKs, including how to download and install them, see <a href="http://aws.amazon.com/tools/">Tools for Amazon Web Services</a>.</p> </note>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: ds
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/ds-2015-04-16.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://ds.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Directory Service multi-region endpoint
- url: https://ds.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Directory Service multi-region endpoint
- url: http://ds.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Directory Service endpoint for China (Beijing) and China (Ningxia)
- url: https://ds.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Directory Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=DirectoryService 20150416.CreateTrust'
paths:
  /#X-Amz-Target=DirectoryService_20150416.CreateTrust:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: CreateTrust
      description: <p>Directory Service for Microsoft Active Directory allows you to configure trust relationships. For example, you can establish a trust between your Managed Microsoft AD directory, and your existing self-managed Microsoft Active Directory. This would allow you to provide users and groups access to resources in either domain, with a single set of credentials.</p> <p>This action initiates the creation of the Amazon Web Services side of a trust relationship between an Managed Microsoft AD directory and an external domain. You can create either a forest trust or an external trust.</p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTrustResult'
        '480':
          description: EntityAlreadyExistsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityAlreadyExistsException'
        '481':
          description: EntityDoesNotExistException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityDoesNotExistException'
        '482':
          description: InvalidParameterException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterException'
        '483':
          description: ClientException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientException'
        '484':
          description: ServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceException'
        '485':
          description: UnsupportedOperationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnsupportedOperationException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTrustRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - DirectoryService_20150416.CreateTrust
      tags:
      - '#X Amz Target=DirectoryService 20150416.CreateTrust'
components:
  schemas:
    ClientException: {}
    CreateTrustResult:
      type: object
      properties:
        TrustId:
          allOf:
          - $ref: '#/components/schemas/TrustId'
          - description: A unique identifier for the trust relationship that was created.
      description: The result of a CreateTrust request.
    UnsupportedOperationException: {}
    DnsIpAddrs:
      type: array
      items:
        $ref: '#/components/schemas/IpAddr'
    InvalidParameterException: {}
    ServiceException: {}
    TrustType:
      type: string
      enum:
      - Forest
      - External
    RemoteDomainName:
      type: string
      pattern: ^([a-zA-Z0-9]+[\\.-])+([a-zA-Z0-9])+[.]?$
    DirectoryId:
      type: string
      pattern: ^d-[0-9a-f]{10}$
    IpAddr:
      type: string
      pattern: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$
    TrustDirection:
      type: string
      enum:
      - 'One-Way: Outgoing'
      - 'One-Way: Incoming'
      - Two-Way
    EntityDoesNotExistException: {}
    TrustId:
      type: string
      pattern: ^t-[0-9a-f]{10}$
    EntityAlreadyExistsException: {}
    CreateTrustRequest:
      type: object
      required:
      - DirectoryId
      - RemoteDomainName
      - TrustPassword
      - TrustDirection
      title: CreateTrustRequest
      properties:
        DirectoryId:
          allOf:
          - $ref: '#/components/schemas/DirectoryId'
          - description: The Directory ID of the Managed Microsoft AD directory for which to establish the trust relationship.
        RemoteDomainName:
          allOf:
          - $ref: '#/components/schemas/RemoteDomainName'
          - description: The Fully Qualified Domain Name (FQDN) of the external domain for which to create the trust relationship.
        TrustPassword:
          allOf:
          - $ref: '#/components/schemas/TrustPassword'
          - description: The trust password. The must be the same password that was used when creating the trust relationship on the external domain.
        TrustDirection:
          allOf:
          - $ref: '#/components/schemas/TrustDirection'
          - description: The direction of the trust relationship.
        TrustType:
          allOf:
          - $ref: '#/components/schemas/TrustType'
          - description: The trust relationship type. <code>Forest</code> is the default.
        ConditionalForwarderIpAddrs:
          allOf:
          - $ref: '#/components/schemas/DnsIpAddrs'
          - description: The IP addresses of the remote DNS server associated with RemoteDomainName.
        SelectiveAuth:
          allOf:
          - $ref: '#/components/schemas/SelectiveAuth'
          - description: Optional parameter to enable selective authentication for the trust.
      description: <p>Directory Service for Microsoft Active Directory allows you to configure trust relationships. For example, you can establish a trust between your Managed Microsoft AD directory, and your existing self-managed Microsoft Active Directory. This would allow you to provide users and groups access to resources in either domain, with a single set of credentials.</p> <p>This action initiates the creation of the Amazon Web Services side of a trust relationship between an Managed Microsoft AD directory and an external domain.</p>
    TrustPassword:
      type: string
      pattern: ^(\p{LD}|\p{Punct}| )+$
      minLength: 1
      maxLength: 128
      format: password
    SelectiveAuth:
      type: string
      enum:
      - Enabled
      - Disabled
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/ds/
x-hasEquivalentPaths: true
